[package]
name = "kvs"
version = "0.1.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]
description = "A key-value store"
edition = "2021"

[dependencies]
clap = "4.5"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
